# ==========================================================
#                üè† HT-Homes+ Configuration
#           Developed with ‚ù§Ô∏è by Mustafa8907
# ==========================================================

language: "en"
teleport-delay: 3
use-placeholder-api: true

# LuckPerms Limitleri (hthomes.limit.<grup>)
home-limits:
  default: 3
  vip: 7
  mvp: 12
  admin: 50

# Eklenti Entegrasyonlarƒ± (Y√ºkl√º deƒüilse otomatik kapanƒ±r)
hooks:
  grief-prevention: true
  world-guard: true
  luck-perms: true

# GUI Materyalleri
icons:
  empty-slot: "RED_BED"
  saved-home: "LIME_BED"
  teleport: "ENDER_PEARL"
  delete: "SKELETON_SKULL"
  back: "BARRIER"
  filler: "GRAY_STAINED_GLASS_PANE"
