name: Build HT-Homes
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4 # v3'ten v4'e yükseltildi

    - name: Set up JDK 8
      uses: actions/setup-java@v4 # v3'ten v4'e yükseltildi
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload HT-Homes Jar
      uses: actions/upload-artifact@v4 # İŞTE KRİTİK NOKTA BURASI: v4 yaptık
      with:
        name: HT-Homes-Plugin
        path: target/HT-Homes.jar
