name: Build HT-Homes
on: [push] # Kod her değiştiğinde otomatik çalışır

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3 # Kodlarını GitHub sunucusuna çeker

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'maven' # Bağımlılıkları önbelleğe alarak derlemeyi hızlandırır

    - name: Build with Maven
      run: mvn clean package # Kodları derler ve .jar oluşturur

    - name: Upload HT-Homes Jar
      uses: actions/upload-artifact@v3
      with:
        name: HT-Homes-Plugin
        path: target/HT-Homes.jar # pom.xml'deki finalName ile uyumlu
